# Generated by Django 3.0.6 on 2020-09-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0115_auto_20200914_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
