# Generated by Django 3.0.6 on 2020-09-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0116_article_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='showname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
